//! Message model: `Envelope`, `Event`, `Control`, `Enc`, `SinceMarker` —
//! ports `model/model.go` plus the bus/e2e wire-format extensions from
//! PLAN.md section 4.1/4.2/7.
//!
//! `control`/`Event::Control` are fully wired up as of M4 (bus extension);
//! `enc`/`encoding` are fully wired up as of M5 (e2e envelope) — the server
//! only ever validates their *shape* (see `http::params::validate_e2e`),
//! never their content: `message`/`title` ciphertext is stored, replayed,
//! and fanned out as an opaque `String`, byte-for-byte.

use rand::Rng;
use serde::{Deserialize, Serialize};
use std::time::{SystemTime, UNIX_EPOCH};

/// Length of a randomly generated message ID (matches ntfy's `messageIDLength`).
pub const MESSAGE_ID_LEN: usize = 12;

const ID_CHARSET: &[u8] = b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

/// Generates a random message ID: 12-character mixed-case alphanumeric,
/// matching ntfy's `util.RandomString`/`GenerateMessageID`. Reused as-is
/// for bus `session_id`s (M4) — same entropy/shape requirements.
pub fn generate_message_id() -> String {
    let mut rng = rand::thread_rng();
    (0..MESSAGE_ID_LEN)
        .map(|_| ID_CHARSET[rng.gen_range(0..ID_CHARSET.len())] as char)
        .collect()
}

/// True if `s` has the shape of an id generated by [`generate_message_id`].
/// Used to distinguish `since=<id>` from `since=<timestamp>`.
pub fn is_valid_message_id(s: &str) -> bool {
    s.len() == MESSAGE_ID_LEN && s.bytes().all(|b| b.is_ascii_alphanumeric())
}

/// Current unix time in seconds.
pub fn now_unix() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64
}

/// Event type of an [`Envelope`]. Ports `model/model.go`'s event constants,
/// plus the bus extension's `control` event (M4).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Event {
    Open,
    Keepalive,
    Message,
    MessageDelete,
    MessageClear,
    PollRequest,
    /// Bus control envelope (join/leave/presence/typing/ack/ping/pong/
    /// error/close) — see [`Control`]. Wired up in M4's `/bus` endpoint.
    Control,
}

/// Bus control-message type (PLAN.md section 4.2).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ControlType {
    /// server -> participants: emitted when a bus participant connects.
    Join,
    /// server -> participants: emitted when a bus participant disconnects.
    Leave,
    /// server -> new participant: full roster snapshot on connect.
    Presence,
    /// client -> relayed to others: ephemeral, never cached.
    Typing,
    /// client -> relayed to others: delivery/read acknowledgement
    /// referencing a message `id` (payload shape is client-defined).
    Ack,
    /// client -> server: app-level heartbeat request.
    Ping,
    /// server -> client: app-level heartbeat reply.
    Pong,
    /// server -> client: malformed frame, rate-limited, permission denied.
    Error,
    /// server -> client: server is terminating the connection.
    Close,
}

/// Bus control-message payload, present on an [`Envelope`] only when
/// `event == Event::Control`. Ports PLAN.md section 4.2's `control` shape:
/// `{ "type": ..., "from": ..., "data": { ... } }`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Control {
    #[serde(rename = "type")]
    pub r#type: ControlType,
    /// Sender label of whoever originated this control message (server
    /// itself uses `"server"` for `join`/`leave`/`presence`/`error`/`close`).
    pub from: String,
    /// Free-form, type-specific payload (e.g. the roster array for
    /// `presence`, or a client-defined ack shape for `ack`).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub data: Option<serde_json::Value>,
}

impl Control {
    pub fn new(r#type: ControlType, from: impl Into<String>) -> Self {
        Self { r#type, from: from.into(), data: None }
    }

    pub fn with_data(mut self, data: serde_json::Value) -> Self {
        self.data = Some(data);
        self
    }
}

/// E2E envelope metadata (PLAN.md section 4.1/7), present on an [`Envelope`]
/// only when `encoding == "e2e"`. Every field is an opaque string from the
/// server's point of view: `alg`/`kid` are free-form client-defined
/// identifiers (never interpreted), and `nonce` is base64 text that the
/// server only shape-checks (decodability + length cap via
/// `http::params::validate_e2e`) — it never attempts to use the nonce for
/// anything, and never touches `message`'s ciphertext content at all.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Enc {
    pub alg: String,
    pub kid: String,
    pub nonce: String,
}

/// The message envelope: superset of ntfy's `model.Message`. See PLAN.md
/// section 4.1 for the wire format this mirrors field-for-field.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Envelope {
    pub id: String,
    pub seq: u64,
    pub time: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires: Option<i64>,
    pub event: Event,
    pub topic: String,
    /// Opaque client-supplied participant/session label (PLAN.md 4.1's
    /// NEW `sender` field). Set on bus-originated `message`/`control`
    /// envelopes as of M4; still `None` for plain HTTP-published messages
    /// (no participant concept there).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sender: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<u8>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub tags: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub click: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    /// "base64" for encoded bytes, "e2e" for opaque ciphertext (M5, see
    /// [`Enc`]). Empty (`None`) means raw UTF-8.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub encoding: Option<String>,
    /// E2E envelope metadata (`alg`/`kid`/`nonce`), only present when
    /// `encoding == "e2e"` (M5). See [`Enc`].
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enc: Option<Enc>,
    /// Bus control payload, present only when `event == Event::Control`
    /// (M4). `None`/omitted for every other event, preserving the M1-era
    /// JSON shape for plain ntfy-compatible clients.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub control: Option<Control>,
}

impl Envelope {
    /// Builds a fresh `message` event envelope. `seq`/`id`/`time` are
    /// allocated by [`crate::topic::Topic::publish`] and passed in here.
    #[allow(clippy::too_many_arguments)]
    pub fn new_message(
        topic: impl Into<String>,
        seq: u64,
        id: String,
        time: i64,
        title: Option<String>,
        message: Option<String>,
        priority: Option<u8>,
        tags: Vec<String>,
        click: Option<String>,
        content_type: Option<String>,
        encoding: Option<String>,
        enc: Option<Enc>,
        expires: Option<i64>,
    ) -> Self {
        Self {
            id,
            seq,
            time,
            expires,
            event: Event::Message,
            topic: topic.into(),
            sender: None,
            title,
            message,
            priority,
            tags,
            click,
            content_type,
            encoding,
            enc,
            control: None,
        }
    }

    /// Builds a `message` event envelope tagged with a bus participant's
    /// `sender` label (PLAN.md 4.1). Used by `Topic::bus_publish_message`.
    /// Accepts `encoding`/`enc` too (M5): PLAN.md doesn't restrict e2e to
    /// HTTP-only publish, so bus participants can send encrypted messages
    /// the same way.
    #[allow(clippy::too_many_arguments)]
    pub fn new_bus_message(
        topic: impl Into<String>,
        seq: u64,
        id: String,
        time: i64,
        sender: String,
        title: Option<String>,
        message: Option<String>,
        priority: Option<u8>,
        tags: Vec<String>,
        click: Option<String>,
        encoding: Option<String>,
        enc: Option<Enc>,
    ) -> Self {
        let mut env = Self::new_message(topic, seq, id, time, title, message, priority, tags, click, None, encoding, enc, None);
        env.sender = Some(sender);
        env
    }

    /// `open` event: sent as the first frame on a live (non-poll) subscribe
    /// stream, including `/bus` connections.
    pub fn open(topic: impl Into<String>) -> Self {
        Self::ephemeral(Event::Open, topic)
    }

    /// `keepalive` event: sent periodically on a live subscribe stream.
    pub fn keepalive(topic: impl Into<String>) -> Self {
        Self::ephemeral(Event::Keepalive, topic)
    }

    /// Builds a `control` event envelope carrying `control`. `seq` is
    /// always `0` (control messages are ephemeral, never persisted/counted
    /// against the topic's sequence — PLAN.md 4.2).
    pub fn control(topic: impl Into<String>, control: Control) -> Self {
        let mut env = Self::ephemeral(Event::Control, topic);
        env.control = Some(control);
        env
    }

    fn ephemeral(event: Event, topic: impl Into<String>) -> Self {
        Self {
            id: generate_message_id(),
            seq: 0,
            time: now_unix(),
            expires: None,
            event,
            topic: topic.into(),
            sender: None,
            title: None,
            message: None,
            priority: None,
            tags: Vec::new(),
            click: None,
            content_type: None,
            encoding: None,
            enc: None,
            control: None,
        }
    }
}

/// Point in time / message ID from which cached messages should be
/// replayed, as parsed from `since=` (ports `model.SinceMarker`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SinceMarker {
    /// No backlog at all (default for live streams without `since=`, and
    /// the default for `/bus` connections per PLAN.md 5.2).
    None,
    /// Every cached message.
    All,
    /// Only the most recently cached message, if any.
    Latest,
    /// Messages with `time >= this timestamp`.
    Time(i64),
    /// Messages strictly after this message ID, in publish order.
    Id(String),
}

impl SinceMarker {
    #[allow(dead_code)]
    pub fn is_none(&self) -> bool {
        matches!(self, SinceMarker::None)
    }
}
