//! Message model: `Envelope`, `Event`, `SinceMarker` — ports `model/model.go`
//! plus the bus/e2e wire-format extensions from PLAN.md section 4.1.
//!
//! `enc` and `control` are always `None` in M1; they are populated for real
//! in M5 (e2e envelope) and M4 (bus control messages) respectively.

use rand::Rng;
use serde::{Deserialize, Serialize};
use std::time::{SystemTime, UNIX_EPOCH};

/// Length of a randomly generated message ID (matches ntfy's `messageIDLength`).
pub const MESSAGE_ID_LEN: usize = 12;

const ID_CHARSET: &[u8] = b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

/// Generates a random message ID: 12-character mixed-case alphanumeric,
/// matching ntfy's `util.RandomString`/`GenerateMessageID`.
pub fn generate_message_id() -> String {
    let mut rng = rand::thread_rng();
    (0..MESSAGE_ID_LEN)
        .map(|_| ID_CHARSET[rng.gen_range(0..ID_CHARSET.len())] as char)
        .collect()
}

/// True if `s` has the shape of an id generated by [`generate_message_id`].
/// Used to distinguish `since=<id>` from `since=<timestamp>`.
pub fn is_valid_message_id(s: &str) -> bool {
    s.len() == MESSAGE_ID_LEN && s.bytes().all(|b| b.is_ascii_alphanumeric())
}

/// Current unix time in seconds.
pub fn now_unix() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs() as i64
}

/// Event type of an [`Envelope`]. Ports `model/model.go`'s event constants,
/// plus the bus extension's `control` event (unreachable until M4).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Event {
    Open,
    Keepalive,
    Message,
    MessageDelete,
    MessageClear,
    PollRequest,
    /// NEW: bus control envelope (join/leave/presence/typing/ack/...).
    /// Not constructed anywhere until M4 wires up `/bus`.
    #[allow(dead_code)]
    Control,
}

/// The message envelope: superset of ntfy's `model.Message`. See PLAN.md
/// section 4.1 for the wire format this mirrors field-for-field.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Envelope {
    pub id: String,
    pub seq: u64,
    pub time: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires: Option<i64>,
    pub event: Event,
    pub topic: String,
    /// NEW: opaque client-supplied participant/session label. Always `None`
    /// until M4 (bus participants).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sender: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<u8>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub tags: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub click: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    /// "base64" for encoded bytes, "e2e" for opaque ciphertext (M5). Empty
    /// (`None`) means raw UTF-8.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub encoding: Option<String>,
    /// NEW: e2e envelope metadata (`alg`/`kid`/`nonce`), only present when
    /// `encoding == "e2e"`. Always `None` until M5.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enc: Option<serde_json::Value>,
    /// NEW: bus control payload, only present when `event == "control"`.
    /// Always `None` until M4.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub control: Option<serde_json::Value>,
}

impl Envelope {
    /// Builds a fresh `message` event envelope. `seq`/`id`/`time` are
    /// allocated by [`crate::topic::Topic::publish`] and passed in here.
    #[allow(clippy::too_many_arguments)]
    pub fn new_message(
        topic: impl Into<String>,
        seq: u64,
        id: String,
        time: i64,
        title: Option<String>,
        message: Option<String>,
        priority: Option<u8>,
        tags: Vec<String>,
        click: Option<String>,
        content_type: Option<String>,
        encoding: Option<String>,
        expires: Option<i64>,
    ) -> Self {
        Self {
            id,
            seq,
            time,
            expires,
            event: Event::Message,
            topic: topic.into(),
            sender: None,
            title,
            message,
            priority,
            tags,
            click,
            content_type,
            encoding,
            enc: None,
            control: None,
        }
    }

    /// `open` event: sent as the first frame on a live (non-poll) subscribe
    /// stream.
    pub fn open(topic: impl Into<String>) -> Self {
        Self::ephemeral(Event::Open, topic)
    }

    /// `keepalive` event: sent periodically on a live subscribe stream.
    pub fn keepalive(topic: impl Into<String>) -> Self {
        Self::ephemeral(Event::Keepalive, topic)
    }

    fn ephemeral(event: Event, topic: impl Into<String>) -> Self {
        Self {
            id: generate_message_id(),
            seq: 0,
            time: now_unix(),
            expires: None,
            event,
            topic: topic.into(),
            sender: None,
            title: None,
            message: None,
            priority: None,
            tags: Vec::new(),
            click: None,
            content_type: None,
            encoding: None,
            enc: None,
            control: None,
        }
    }
}

/// Point in time / message ID from which cached messages should be
/// replayed, as parsed from `since=` (ports `model.SinceMarker`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SinceMarker {
    /// No backlog at all (default for live streams without `since=`).
    None,
    /// Every cached message.
    All,
    /// Only the most recently cached message, if any.
    Latest,
    /// Messages with `time >= this timestamp`.
    Time(i64),
    /// Messages strictly after this message ID, in publish order.
    Id(String),
}

impl SinceMarker {
    #[allow(dead_code)]
    pub fn is_none(&self) -> bool {
        matches!(self, SinceMarker::None)
    }
}
